version: '2'
services:
    novnc:
      privileged: true
      image: vm:latest
      build:
        context: ./
        dockerfile: Dockerfile
      environment:
        - DISPLAY=:0
        - HTTP_PASSWORD=secret
        - VNC_PASSWORD=secret
      ports:
        - 6080:6080
        - 5900:5900
      volumes:
        - avd:/home/avd/.android/avd
        - system-images:/home/avd/android-sdk/system-images
        - platforms:/home/avd/android-sdk/platforms
volumes:
  avd:
  system-images:
  platforms:
